pool:
  vmImage: ubuntu-latest # Use 'windows-latest' if you have Windows native +Node modules
steps:
- bash: |
    if [ -f extensions.csproj ]
    then
        dotnet build extensions.csproj --output ./bin
    fi
    ls -l
    pwd
    echo $(Agent.BuildDirectory)
    #cd $(Agent.BuildDirectory)/node/plain/functionApp/Tests
    npm install 
    npm run build --if-present
    npm prune --production